/*
 * SPI_cfg.c
 *
 *  Created on: Sep 14, 2023
 *      Author: E0162112
 */

#include "SPI_cfg.h"

SPI_ConfigParam_t SPI_ConfigParams =
{
		.CPHA = SPI_READ_SECOND, .CPOL = SPI_IDLE_LOW, .MSTR = SPI_MASTER, .BR = SPI_FpClk_DIV_32, .SPE = SPI_ENABLE, \
		.LSBFIRST = SPI_LSB_FIRST, .SSM = SPI_DISABLE, .RXONLY = SPI_DISABLE, .DFF = SPI_8BITS, .CRCNEXT = SPI_DISABLE,\
		.CRCEN = SPI_DISABLE , .BIDIOE = SPI_DISABLE , .BIDIMODE = SPI_2_LINE_UNI ,.RXDMAEN = SPI_DISABLE, .TXDMAEN = SPI_DISABLE,\
		.SSOE = SPI_ENABLE, .ERRIE = SPI_ENABLE, .RXNEIE = SPI_DISABLE, .TXEIE = SPI_DISABLE
};

